version: "3.8"

services:
  chatbot:
    image: chatbot:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot
    ports:
      - "12345:12345"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: python app.py
